version: '3.9'
services:
  rest:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: rest
    entrypoint: ./services/rest/rest/server

    environment:
      - PORT=3100

    ports:
      - "3100:3100"

  users-rest:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: users-rest
    entrypoint: ./services/rest/users/server

    environment:
      - PORT=3101

    ports:
      - "3101:3101"

  posts-rest:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: posts-rest
    entrypoint: ./services/rest/posts/server

    environment:
      - PORT=3102

    ports:
      - "3102:3102"

  comments-rest:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: comments-rest
    entrypoint: ./services/rest/comments/server

    environment:
      - PORT=3103

    ports:
      - "3103:3103"

  users-subgraph:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: users-subgraph
    entrypoint: ./services/graphql-subgraphs/users/server

    environment:
      - PORT=4201

    ports:
      - "4201:4201"

  posts-subgraph:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: posts-subgraph
    entrypoint: ./services/graphql-subgraphs/posts/server

    environment:
      - PORT=4202

    ports:
      - "4202:4202"

  comments-subgraph:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: comments-subgraph
    entrypoint: ./services/graphql-subgraphs/comments/server

    environment:
      - PORT=4203

    ports:
      - "4203:4203"

  notifications-subgraph:
    image: zalbiraw/go-api-test-service:v2.0.0
    container_name: notifications-subgraph
    entrypoint: ./services/graphql-subgraphs/notifications/server

    environment:
      - PORT=4204

    ports:
      - "4204:4204"